kind: pipeline
type: docker
name: build-dev
steps:
  - name: build-app
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      tags:
        - latest
      registry:
        from_secret: registry_uri
      username:
        from_secret: registry_login
      password:
        from_secret: registry_password
      repo: rg.fr-par.scw.cloud/cypios/cypios-account
    commands: []
trigger:
  branch:
    - master

---
kind: pipeline
type: docker
name: build-prod
steps:
  - name: build-app
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      auto_tag: true
      registry:
        from_secret: registry_uri
      username:
        from_secret: registry_login
      password:
        from_secret: registry_password
      repo: rg.fr-par.scw.cloud/cypios/cypios-account
    commands: []
trigger:
  event:
    - tag
