kind: pipeline
type: docker
name: build-docker

steps:
  - name: build-app
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      auto_tag: true
      registry:
        from_secret: registry_uri
      username:
        from_secret: registry_login
      password:
        from_secret: registry_password
      repo: rg.fr-par.scw.cloud/cypios/cypios-account
    commands: []
