{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-svc.fullname" . }}
  labels:
    {{- include "app-svc.labels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
    {{- if (eq .Values.service.type "ClusterIP") }}
      nodePort: null
    {{- end }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "app-svc.selectorLabels" . | nindent 4 }}
{{- end }}
