templates:
  default-service-release: &default-service-release
    chart: './app-svc-{{ requiredEnv "SemVer" }}.tgz'
    version: '{{ requiredEnv "SemVer" }}'
    namespace: '{{ .Values.namespace }}'
    missingFileHandler: Error
    labels:
      tier: backend
    values:
      - values/default-values.yaml.gotmpl
      - values/{{ .Release.Name }}/{{ .Environment.Name }}.yaml.gotmpl