export const confirmPro = "https://sso.dev.cypios.net/sso/pro/confirm"
export const confirmPatient = "https://sso.dev.cypios.net/sso/patient/confirm"
export const createPro = "https://sso.dev.cypios.net/sso/pro/invite"
export const resetPassword = "https://sso.dev.cypios.net/sso/global/reset"
export const enterPassword = "https://sso.dev.cypios.net/sso/global/change"
export const resetEmail = "https://sso.dev.cypios.net/sso/global/email/change"