steps:
  - task: UseDotNet@2
    inputs:
      packageType: "sdk"
      version: 6.0.x
  - bash: |
      dotnet new tool-manifest
      dotnet tool install GitVersion.Tool --version 5.*
      dotnet gitversion /output buildserver
    displayName: Update Version
  - bash: |
      echo "##vso[task.setvariable variable=FullBuildMetaData;isOutput=true]$GITVERSION_FULLBUILDMETADATA"
      echo "##vso[task.setvariable variable=InformationalVersion;isOutput=true]$GITVERSION_INFORMATIONALVERSION"
      echo "##vso[task.setvariable variable=FullSemVer;isOutput=true]$GITVERSION_FULLSEMVER"
      echo "##vso[task.setvariable variable=SemVer;isOutput=true]$GITVERSION_SEMVER"
      echo "##vso[task.setvariable variable=ShortSha;isOutput=true]$GITVERSION_SHORTSHA"
    displayName: Update version variables
    name: UpdateSemver