parameters:
  - name: azureSubscription
    type: string

  - name: labels
    default: "tier=backend"

steps:
- checkout: self 
  fetchDepth: 1
- download: none
- task: AzureCLI@2
  displayName: Setup kubectl
  inputs:
    azureSubscription: ${{ parameters.azureSubscription }}
    scriptLocation: inlineScript
    scriptType: bash
    inlineScript: |
      az aks install-cli
      az aks get-credentials --resource-group $(azure_rg) -n $(azure_aks)

- script: |
    curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash -s -- -v $(HELM_VERSION)
    sudo wget -q https://github.com/roboll/helmfile/releases/download/$(HELMFILE_VERSION)/helmfile_linux_amd64 -O /usr/local/bin/helmfile && \
      sudo chmod +x /usr/local/bin/helmfile
    helm plugin install https://github.com/databus23/helm-diff --version 3.1.3
  displayName: Setup helm
  name: helmSetup
- script: |
    set -x
    export SemVer=$(SemVer)
    export CYPIOS_DEFAULT_VERSION=$(FullBuildMetaData)
    helmfile -e $(envName) -l ${{ parameters.labels }} apply
  # env:
    # map env variables used in helmfile by multiple services

  workingDirectory: helmfile
  displayName: helmfile apply
