name: $(SourceBranchName)_$(Date:yyyyMMddhhmm)$(rev:.rr)

trigger:
  branches:
    include:
      - main
      - master
      - develop
      - release/*
      

parameters:
  - name: CypiosEnv
    displayName: Targent environment
    type: string    
    default: None
    values:
      - None
      - Develop
      - Prod
      - Staging
      - Test

pool:
  vmImage: 'ubuntu-latest'

stages:
                 
- stage: deploy
  jobs:
    - job: init # Placeholder job to initialize the deploy stage and avoid errors
      condition: false
      steps:
        - checkout: none 
        - bash: |
            echo "init"

    - ${{ if or(eq(parameters.CypiosEnv, 'Develop'), and(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['Build.Reason'], 'IndividualCI')) ) }}:
        - deployment: deployDev
          environment: Develop.cypios-services-develop
          variables:
            - group: Develop
            - group: Front-Account-Develop
          strategy:
            runOnce:
              deploy:
                steps:
                  - checkout: self 
                  - template: "templates/staticwebapp-build.yaml"

    - ${{ if or(eq(parameters.CypiosEnv, 'Prod'), and(in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/main'), eq(variables['Build.Reason'], 'IndividualCI')) ) }}:
        - job: manualValidation        
          displayName: 'Waiting for manual validation'
          pool: server
          timeoutInMinutes: 4320 # job times out in 3 days
          steps:
          - task: ManualValidation@0
            inputs:
              # notifyUsers should be a distribution group or sahred mailbox
              notifyUsers: |
                p.joyeau@cypios.fr
                q.thomas@cypios.fr
                t.florentin@cypios.fr                
              instructions: 'Please validate the deployement on production envrironnement'

        - deployment: deployProd
          dependsOn: manualValidation
          environment: Prod.cypios-services-prod
          variables:
            - group: Prod
            - group: Front-Account-Prod
          strategy:
            runOnce:
              deploy:
                steps:
                  - checkout: self 
                  - template: "templates/staticwebapp-build.yaml"

    - ${{ if or(eq(parameters.CypiosEnv, 'Staging'), and(startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'), eq(variables['Build.Reason'], 'IndividualCI')) ) }}:
        - deployment: deployStaging
          environment: Staging.cypios-services-staging
          variables:
            - group: Staging
            - group: Front-Account-Staging
          strategy:
            runOnce:
              deploy:
                steps:
                  - checkout: self 
                  - template: "templates/staticwebapp-build.yaml"

    - ${{ if eq(parameters.CypiosEnv, 'Test') }}:
        - deployment: deployTest
          environment: Test.cypios-services-test
          variables:
            - group: Test
            - group: Front-Account-Test
          strategy:
            runOnce:
              deploy:
                steps:
                  - checkout: self
                  - template: "templates/staticwebapp-build.yaml"

    - ${{ if and(eq(parameters.CypiosEnv, 'None'), ne(variables['Build.Reason'], 'IndividualCI') ) }}:
      - deployment: buildWithoutDeployment
        environment: Develop.cypios-services-develop
        variables:
          - group: Develop          
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: "templates/staticwebapp-build.yaml"
                  parameters:
                    Deploy: false                   